languageCode = "en"
languageName = "English"
weight = 1
title = " Digital Crunch - AI Systems. Leads. Sales. 24x7."

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/img/dc_logo.png"
  description = "We solve technical problems, with a smile!"

[params.author]
  name = "James Fraze"
  email = "james@jamesfraze.com"
  image = "/img/jamesfraze.jpg"
  headline = "Principal AI Engineer"
  bio = "I solve technical problems, with a smile!"
  links = [
    { "linkedin" = "https://linkedin.com/in/digitalcrunch" },
    { "twitter" = "https://twitter.com/frazemarketing" },
    { "instagram" = "https://instagram.com/frazemarketing" },
    { "github" = "https://github.com/rubysash" }
  ]
