# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#--------
# 10
#--------
[[main]]
  identifier = "contact"
  name = "(945) 245-4257 "
  pre = "phone"
  url = "tel:+19452454257"
  weight = 10

#--------
# 20
#--------
[[main]]
  name = "Services"
  pageRef = "services"
  weight = 20

[[main]]
  name = "AI Bots"
  parent = "Services"
  pageRef = "services/ai-bots"
  weight = 105

[[main]]
  name = "AI Lead Generation"
  parent = "Services"
  pageRef = "services/ai-lead-generation"
  weight = 107

[[main]]
  name = "AI Reputation"
  parent = "Services"
  pageRef = "services/ai-reputation"
  weight = 109

[[main]]
  name = "AI Search"
  parent = "Services"
  pageRef = "services/schema-validation"
  weight = 110

[[main]]
  name = "AI Security"
  parent = "Services"
  pageRef = "services/ai-security"
  weight = 112

[[main]]
  name = "AI Automation"
  parent = "Services"
  pageRef = "services/ai-automation"
  weight = 113

[[main]]
  name = "Custom Scripting"
  parent = "Services"
  pageRef = "services/custom-scripting"
  weight = 114

#--------
# 30
#--------
[[main]]
  name = "Research"
  pageRef = "research"
  weight = 30

[[main]]
  name = "Schema"
  parent = "Research"
  pageRef = "research/schema"
  weight = 10

[[main]]
  name = "Quick FAQs"
  parent = "Research"
  pageRef = "research/quick-faqs"
  weight = 20

[[main]]
  name = "Free Tools"
  parent = "Research"
  pageRef = "research/free-tools"
  weight = 30







#[[main]]
#  identifier = "x"
#  pre = "x-twitter"
#  url = "https://x.com/frazemarketing"
#  weight = 200

#[[main]]
#  identifier = "instagram"
#  pre = "instagram"
#  weight = 300
#  url = "https://instagram.com/frazemarketing"


#[[main]]
#  identifier = "linkedin"
#  pre = "linkedin"
#  url = "https://linkedin.com/in/digitalcrunch"
# weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "About"
   pageRef = "about"
   weight = 20

 [[footer]]
   name = "Privacy Policy"
   pageRef = "privacy-policy"
   weight = 30

 [[footer]]
   name = "Accessibility"
   pageRef = "accessibility"
   weight = 40

 [[footer]]
   name = "Cookie Policy"
   pageRef = "cookie-policy"
   weight = 50


 [[footer]]
   name = "Terms of Service"
   pageRef = "terms-of-service"
   weight = 60
