# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 5

[[main]]
  name = "AI Bots"
  parent = "Services"
  pageRef = "ai-bots"
  weight = 16

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  identifier = "contact"
  name = "(945) 245-4257 "
  pre = "phone"
  url = "tel:+19452454257"
  weight = 50

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 15

#[[main]]
#  identifier = "x"
#  pre = "x-twitter"
#  url = "https://x.com/frazemarketing"
#  weight = 200

#[[main]]
#  identifier = "instagram"
#  pre = "instagram"
#  weight = 300
#  url = "https://instagram.com/frazemarketing"


#[[main]]
#  identifier = "linkedin"
#  pre = "linkedin"
#  url = "https://linkedin.com/in/digitalcrunch"
# weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20

 [[footer]]
   name = "Privacy Policy"
   pageRef = "privacy-policy"
   weight = 25

 [[footer]]
   name = "Accessibility"
   pageRef = "accessibility"
   weight = 15

 [[footer]]
   name = "Cookie Policy"
   pageRef = "cookie-policy"
   weight = 20


 [[footer]]
   name = "Terms of Service"
   pageRef = "terms-of-service"
   weight = 30
